import os
from dotenv import load_dotenv

load_dotenv()

ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY", "")

CV_FOLDER = os.path.join(os.path.dirname(__file__), "resumes")
DATA_DIR = os.path.join(os.path.dirname(__file__), "data")
TEMPLATES_DIR = os.path.join(os.path.dirname(__file__), "templates")

PROFILE_PATH = os.path.join(DATA_DIR, "profile.json")
APPLICATIONS_PATH = os.path.join(DATA_DIR, "applications.json")

CLAUDE_FAST = "claude-haiku-4-5-20251001"
CLAUDE_SMART = "claude-sonnet-4-6"

JOB_SEARCH_CACHE_TTL = 1800  # 30 minutes

TARGET_ROLES = [
    "Data Analyst", "Business Analyst", "Product Analyst",
    "Strategy Analyst", "BizOps", "RevOps", "Operations Analyst",
    "BI Analyst", "Analytics Engineer", "Growth Analyst",
]

# ── Role categories for job search ───────────────────────────────────────────
# Each category contains ALL title variations (full names + abbreviations)
# so we don't miss jobs due to different naming conventions.
ROLE_CATEGORIES = {
    "📊 Data & Analytics": [
        "Data Analyst", "Data Analysis", "Analytics Analyst",
        "Business Intelligence Analyst", "BI Analyst", "BI Developer",
        "Intelligence Analyst", "Insights Analyst", "Reporting Analyst",
        "Product Analyst", "Growth Analyst", "Marketing Analyst",
        "Commercial Analyst", "Data Specialist", "Analytics Specialist",
        "Analytics Engineer", "Data Engineer",
    ],
    "💼 Business & Operations": [
        "Business Analyst", "Business Analysis",
        "Business Process Analyst", "Process Improvement Analyst",
        "Operations Analyst", "Business Operations", "Business Operations Analyst",
        "Operational Excellence", "Operations Specialist",
        "Revenue Operations", "Revenue Operations Analyst",
        "Sales Operations", "Sales Operations Analyst",
        "GTM Operations", "Go to Market Operations",
        "BizOps", "RevOps",
        "Strategy Analyst", "Corporate Strategy", "Business Strategy",
        "Management Analyst",
    ],
    "🚀 Product & Strategy": [
        "Product Analyst", "Product Data Analyst",
        "Product Operations", "Product Operations Analyst",
        "Product Strategy", "Product Strategy Analyst",
        "Growth Analyst", "Growth Manager",
        "Commercial Analyst", "Customer Success Operations",
        "CX Operations", "Customer Operations",
    ],
    "💰 Finance & Investment": [
        "Financial Analyst", "Finance Analyst", "Junior Analyst",
        "Corporate Finance Analyst", "FP&A Analyst",
        "Financial Planning", "Treasury Analyst",
        "Investment Analyst", "Portfolio Analyst", "Fund Analyst",
        "Asset Management Analyst", "Capital Markets Analyst",
        "Equity Research Analyst", "Research Analyst", "Equity Analyst",
        "Venture Capital Analyst", "VC Analyst",
        "Private Equity Analyst", "PE Analyst",
        "Hedge Fund Analyst",
        "Risk Analyst", "Credit Analyst", "Quantitative Analyst",
        "M&A Analyst", "Mergers and Acquisitions Analyst",
    ],
}

# Broad queries sent to each job source per category (broad = fewer API calls)
PRIMARY_QUERIES = {
    "📊 Data & Analytics":     ["analyst", "business intelligence", "analytics"],
    "💼 Business & Operations": ["operations analyst", "business analyst", "operations"],
    "🚀 Product & Strategy":    ["product analyst", "product operations"],
    "💰 Finance & Investment":  ["investment analyst", "financial analyst", "portfolio analyst"],
}

# Hebrew queries for the Hebrew-language job boards (AllJobs/Drushim/JobMaster).
# These are NOT literal translations of the English titles above — they were
# validated by actually querying the boards and reading real returned listings.
# E.g. the literal translation of "Business Analyst" ("מנתח עסקי") mostly returns
# Systems Analyst postings in practice; the real term Israeli employers use is
# "אנליסט עסקי". Written as plain space-separated stems (no gender-suffix
# notation) — the matching layer in job_search.py normalizes suffix notation
# (e.g. "אנליסט/ית", "אנליסט.ית") automatically.
PRIMARY_QUERIES_HE = {
    "📊 Data & Analytics":     ["אנליסט נתונים", "דאטה אנליסט", "אנליסט BI"],
    "💼 Business & Operations": ["אנליסט עסקי", "אנליסט תפעולי"],
    "🚀 Product & Strategy":    ["אנליסט צמיחה", "אנליסט מוצר"],
    "💰 Finance & Investment":  ["כלכלן", "אנליסט פיננסי", "אנליסט השקעות", "אנליסט סיכונים", "אנליסט אשראי"],
}

# Post-filter keywords: job title must contain at least one of these
MATCH_KEYWORDS = {
    "📊 Data & Analytics": [
        "data analyst", "data analysis", "analytics", "business intelligence",
        "bi analyst", "bi developer", "insights analyst", "reporting analyst",
        "product analyst", "growth analyst", "marketing analyst",
        "commercial analyst", "data specialist", "analytics engineer",
        "intelligence analyst", "big data analyst",
    ],
    "💼 Business & Operations": [
        "business analyst", "business analysis", "operations analyst",
        "business operations", "process analyst", "process improvement",
        "revenue operations", "sales operations", "gtm operations",
        "bizops", "revops", "strategy analyst", "management analyst",
        "operational excellence", "operations specialist",
    ],
    "🚀 Product & Strategy": [
        "product analyst", "product operations", "product strategy",
        "growth analyst", "customer success operations", "cx operations",
        "customer operations", "product data",
    ],
    "💰 Finance & Investment": [
        "financial analyst", "investment analyst", "portfolio analyst",
        "fund analyst", "equity research", "research analyst",
        "capital markets", "venture capital", "private equity",
        "hedge fund", "risk analyst", "credit analyst",
        "m&a analyst", "fp&a", "treasury analyst", "junior analyst",
        "asset management", "quantitative analyst",
    ],
}

# Hebrew title-matching phrases per category (post-filter), same validation
# discipline as PRIMARY_QUERIES_HE above — real observed terms, not translations.
MATCH_KEYWORDS_HE = {
    "📊 Data & Analytics": [
        "אנליסט נתונים", "דאטה אנליסט", "אנליסט BI", "רפרנט BI",
        "אנליסט תמחור", "אנליסט קמפיינים",
    ],
    "💼 Business & Operations": [
        "אנליסט עסקי", "אנליסט תפעולי", "אנליסט תכנון", "אנליסט לוגיסטיקה",
    ],
    "🚀 Product & Strategy": [
        "אנליסט צמיחה", "אנליסט מוצר", "אנליסט קמפיינים",
    ],
    "💰 Finance & Investment": [
        "כלכלן", "אנליסט פיננסי", "אנליסט השקעות", "אנליסט סיכונים",
        "אנליסט אשראי", "בקרה תקציבית", "בקר תקציב",
    ],
}

# Experience level filter settings
EXPERIENCE_LEVELS = {
    "All Levels": {"alljobs_code": "", "drushim_code": "0"},
    "Entry (0-2 שנים)": {"alljobs_code": "1", "drushim_code": "1"},
    "Mid (2-5 שנים)":   {"alljobs_code": "2", "drushim_code": "2"},
}

# Titles to exclude per experience level (applied to Greenhouse/Lever results)
EXPERIENCE_EXCLUDE = {
    "Mid (2-5 שנים)":   ["director", "vp ", "vice president", "head of", "principal", "staff engineer", "10+ years", "8+ years"],
    "Entry (0-2 שנים)": ["director", "vp ", "vice president", "head of", "principal", "staff engineer", "10+ years", "8+ years", "senior", "7+ years", "6+ years", "5+ years"],
}

KANBAN_STAGES = ["Saved", "Applied", "Phone Screen", "Interview", "Offer", "Rejected"]

# ── Recruitment agencies ─────────────────────────────────────────────────────
RECRUITMENT_AGENCIES = [
    {"name": "JobMaster",      "he": "ג'ובמסטר",   "url": "https://www.jobmaster.co.il/",  "alljobs_search": "https://www.alljobs.co.il/SearchResultsGuest.aspx?Company=JobMaster",   "specialties": ["Tech", "Finance", "Analytics"]},
    {"name": "SuperAgent",     "he": "סופרגנט",     "url": "https://www.superagent.co.il/", "alljobs_search": "https://www.alljobs.co.il/SearchResultsGuest.aspx?Company=SuperAgent",  "specialties": ["Analytics", "BizOps"]},
    {"name": "Malam Team",     "he": "מלם תים",     "url": "https://www.malamteam.com/",    "alljobs_search": "https://www.alljobs.co.il/SearchResultsGuest.aspx?Company=Malam+Team", "specialties": ["Tech", "BI", "Data"]},
    {"name": "Manpower IL",    "he": "מנפאואר",     "url": "https://www.manpower.co.il/",   "alljobs_search": "https://www.alljobs.co.il/SearchResultsGuest.aspx?Company=Manpower",   "specialties": ["Finance", "Operations"]},
    {"name": "Hito",           "he": "היטו",         "url": "https://www.hito.co.il/",       "alljobs_search": "https://www.alljobs.co.il/SearchResultsGuest.aspx?Company=Hito",       "specialties": ["Tech", "Product", "Analytics"]},
    {"name": "Approach",       "he": "אפרוץ'",       "url": "https://www.approach.co.il/",   "alljobs_search": "https://www.alljobs.co.il/SearchResultsGuest.aspx?Company=Approach",   "specialties": ["Finance", "Accounting"]},
    {"name": "Experis",        "he": "אקספריס",      "url": "https://www.experis.co.il/",    "alljobs_search": "https://www.alljobs.co.il/SearchResultsGuest.aspx?Company=Experis",    "specialties": ["Tech", "BI", "Data"]},
    {"name": "Aman Consulting", "he": "אמן ייעוץ",  "url": "https://www.aman.co.il/",       "alljobs_search": "https://www.alljobs.co.il/SearchResultsGuest.aspx?Company=Aman",       "specialties": ["Strategy", "Operations", "Analytics"]},
    {"name": "BDO Ziv Haft",   "he": "BDO זיו האפט","url": "https://www.bdo.co.il/career",  "alljobs_search": "https://www.alljobs.co.il/SearchResultsGuest.aspx?Company=BDO",        "specialties": ["Finance", "Analytics"]},
    {"name": "Gitam Porter",   "he": "גיתם פורטר",  "url": "https://www.gpn.co.il/careers", "alljobs_search": "https://www.alljobs.co.il/SearchResultsGuest.aspx?Company=Gitam",      "specialties": ["Strategy", "Business"]},
]


# ── Israeli companies by sector (193 companies from Grand Master Matrix) ──────────────
ISRAELI_COMPANIES = {
    '🏛️ VC & Private Equity': [
        {"name": 'Viola Group', "he": 'ויולה', "url": 'https://www.violagroup.com', "location": 'Herzliya'},
        {"name": 'Pitango VC', "he": 'פיטנגו', "url": 'https://www.pitango.com', "location": 'Herzliya'},
        {"name": 'Team8', "he": 'טים8', "url": 'https://team8.vc', "location": 'Tel Aviv', "comeet": ('url', 'team8', '61.003')},
        {"name": 'Aleph VC', "he": 'אלף', "url": 'https://aleph.vc', "location": 'Tel Aviv'},
        {"name": 'TLV Partners', "url": 'https://www.tlv.partners', "location": 'Tel Aviv'},
        {"name": 'Glilot Capital Partners', "he": 'גלילות', "url": 'https://glilotcapital.com', "location": 'Herzliya'},
        {"name": 'Entrée Capital', "url": 'https://entreecap.com', "location": 'Tel Aviv'},
        {"name": 'Qumra Capital', "he": 'קומרה', "url": 'https://qumracapital.com', "location": 'Tel Aviv'},
        {"name": 'Vintage Investment Partners', "url": 'https://www.vintageip.com', "location": 'Herzliya'},
        {"name": 'Cyberstarts', "url": 'https://cyberstarts.com', "location": 'Tel Aviv'},
        {"name": 'JVP', "he": 'Jerusalem Venture Partners', "url": 'https://www.jvpvc.com', "location": 'Tel Aviv'},
        {"name": 'OurCrowd', "url": 'https://www.ourcrowd.com', "location": 'Tel Aviv', "comeet": ('widget', 'D3.00A', '3DA1342F683DA22AAF683DAF68F68F68')},
        {"name": 'Vertex Ventures Israel', "url": 'https://www.vertexventures.sg/israel', "location": 'Tel Aviv / Herzliya'},
        {"name": 'Magma Venture Partners', "url": 'https://magmavp.com', "location": 'Tel Aviv'},
    ],
    '📈 Investment Houses': [
        {"name": 'ION Asset Management', "he": 'איון', "url": 'https://www.ion-am.com', "location": 'Herzliya'},
        {"name": 'Sphera Funds Management', "he": 'ספירה', "url": 'https://www.spherafunds.com', "location": 'Tel Aviv'},
        {"name": 'Noked Capital', "he": 'נוקד קפיטל', "url": 'https://www.nokedcapital.com', "location": 'Tel Aviv'},
        {"name": 'Tzur Management', "he": 'צור ניהול קרנות', "url": 'https://www.tzurmanagement.com', "location": 'Tel Aviv'},
        {"name": 'Alpha Beta', "he": 'אלפא ביתא', "url": 'https://www.alphabeta.co.il', "location": 'Tel Aviv'},
        {"name": 'Meitav', "he": 'מיטב דש', "url": 'https://www.meitav.co.il', "location": 'Bnei Brak (BBC)'},
        {"name": 'IBI Investment House', "he": 'אי-בי-אי', "url": 'https://www.ibi.co.il', "location": 'Tel Aviv'},
        {"name": 'Altshuler Shaham', "he": 'אלטשולר שחם', "url": 'https://www.asg.co.il', "location": 'Tel Aviv'},
        {"name": 'Yalin Lapidot', "he": 'ילין לפידות', "url": 'https://www.yl-invest.co.il', "location": 'Tel Aviv'},
        {"name": 'Analyst Investment House', "he": 'אנליסט', "url": 'https://www.analyst.co.il', "location": 'Tel Aviv'},
        {"name": 'Excellence Investment House', "he": 'אקסלנס', "url": 'https://www.xln.co.il', "location": 'Petah Tikva'},
        {"name": 'Psagot Investment House', "he": 'פסגות', "url": 'https://www.psagot.co.il', "location": 'Tel Aviv'},
        {"name": 'More Investment House', "he": 'מור בית השקעות', "url": 'https://www.moreinvest.co.il', "location": 'Tel Aviv'},
        {"name": 'Ayalon Investment House', "he": 'איילון בית השקעות', "url": 'https://www.ayalon-invest.co.il', "location": 'Tel Aviv'},
        {"name": 'Tamir Fishman', "he": 'תמיר פישמן', "url": 'https://tamirfishman.co.il', "location": 'Tel Aviv'},
    ],
    '🏢 Capital Markets': [
        {"name": 'Poalim Capital Markets', "he": 'פועלים שוקי הון', "url": 'https://www.poalimcm.co.il', "location": 'Tel Aviv'},
        {"name": 'Leumi Partners', "he": 'לאומי פרטנרס', "url": 'https://www.leumipartners.com', "location": 'Tel Aviv'},
        {"name": 'Discount Capital', "he": 'דיסקונט קפיטל', "url": 'https://www.dcapital.co.il', "location": 'Tel Aviv'},
        {"name": 'Barak Capital', "he": 'ברק קפיטל', "url": 'https://www.barakcapital.com', "location": 'Tel Aviv'},
        {"name": 'Oppenheimer Israel', "he": 'אופנהיימר', "url": 'https://www.oppenheimer.co.il', "location": 'Tel Aviv'},
        {"name": 'Giza Singer Even', "he": 'גיזה זינגר אבן', "url": 'https://www.giza.co.il', "location": 'Tel Aviv'},
        {"name": 'Leader Capital Markets', "he": 'לידר שוקי הון', "url": 'https://leadercm.com', "location": 'Tel Aviv'},
        {"name": 'Migdal Capital Markets', "he": 'מגדל שוקי הון', "url": 'https://my.migdal.co.il/en/capital-markets/', "location": 'Petah Tikva'},
    ],
    '🏦 Banks & Insurance': [
        {"name": 'Bank Leumi', "he": 'לאומי', "url": 'https://www.leumi.co.il', "location": 'Tel Aviv'},
        {"name": 'Bank Hapoalim', "he": 'פועלים', "url": 'https://www.bankhapoalim.co.il', "location": 'Tel Aviv'},
        {"name": 'Mizrahi-Tefahot Bank', "url": 'https://www.mizrahi-tefahot.co.il', "location": 'Ramat Gan'},
        {"name": 'First International Bank', "he": 'בינלאומי', "url": 'https://www.fibi.co.il', "location": 'Tel Aviv'},
        {"name": 'One Zero Digital Bank', "url": 'https://www.onezero.co.il', "location": 'Tel Aviv'},
        {"name": 'Isracard', "he": 'ישראכרט', "url": 'https://digital.isracard.co.il', "location": 'Tel Aviv'},
        {"name": 'Plus500', "url": 'https://www.plus500.com', "location": 'Tel Aviv'},
        {"name": 'Fundbox', "url": 'https://fundbox.com', "location": 'Tel Aviv'},
        {"name": 'BlueVine', "url": 'https://www.bluevine.com', "location": 'Tel Aviv'},
        {"name": 'The Phoenix', "he": 'הפניקס', "url": 'https://www.fnx.co.il', "location": 'Givatayim'},
        {"name": 'Harel Insurance', "he": 'הראל', "url": 'https://www.harel-group.co.il', "location": 'Ramat Gan'},
        {"name": 'Menora Mivtachim', "he": 'מנורה', "url": 'https://www.menoramivt.co.il', "location": 'Ramat Gan'},
        {"name": 'Clal Insurance', "he": 'כלל', "url": 'https://www.clalbit.co.il', "location": 'Tel Aviv'},
        {"name": 'Migdal Insurance', "he": 'מגדל', "url": 'https://www.migdal.co.il', "location": 'Petah Tikva'},
        {"name": 'Direct Insurance', "he": 'ביטוח ישיר', "url": 'https://www.555.co.il', "location": 'Bnei Brak'},
        {"name": 'Libra Insurance', "he": 'ליברה', "url": 'https://www.libra-insurance.co.il', "location": 'Holon'},
        {"name": 'WeSure Global', "he": 'ווישור', "url": 'https://www.we-sure.co.il', "location": 'Petah Tikva'},
    ],
    '💳 FinTech': [
        {"name": 'Max', "he": 'מקס', "url": 'https://www.max.co.il', "location": 'Bnei Brak (BBC)'},
        {"name": 'eToro', "url": 'https://www.etoro.com', "location": 'Bnei Brak (BBC)', "comeet": ('widget', '41.009', '14952452466D3DB7B61495240B91')},
        {"name": 'Payoneer', "url": 'https://www.payoneer.com', "location": 'Herzliya', "greenhouse": 'payoneer'},
        {"name": 'Tipalti', "url": 'https://tipalti.com', "location": 'Herzliya / Glil Yam'},
        {"name": 'Pagaya', "url": 'https://pagaya.com', "location": 'Tel Aviv / Bnei Brak', "greenhouse": 'pagaya'},
        {"name": 'DataRails', "url": 'https://www.datarails.com', "location": 'Tel Aviv'},
        {"name": 'Liquidity Group', "url": 'https://liquidity.com', "location": 'Tel Aviv'},
    ],
    '💼 Consulting': [
        {"name": 'McKinsey & Company Israel', "url": 'https://www.mckinsey.com', "location": 'Tel Aviv'},
        {"name": 'Boston Consulting Group Israel', "he": 'BCG', "url": 'https://www.bcg.com', "location": 'Tel Aviv'},
        {"name": 'Bain & Company Israel', "url": 'https://www.bain.com', "location": 'Tel Aviv'},
        {"name": 'TASC Management Consulting', "url": 'https://www.tasc-consulting.com', "location": 'Tel Aviv'},
        {"name": 'Deloitte Israel', "url": 'https://www.deloitte.co.il', "location": 'Tel Aviv'},
        {"name": 'EY Israel', "he": 'Ernst & Young', "url": 'https://www.ey.com', "location": 'Tel Aviv'},
        {"name": 'PwC Israel', "url": 'https://www.pwc.com', "location": 'Tel Aviv'},
        {"name": 'KPMG Israel', "url": 'https://kpmg.com', "location": 'Tel Aviv'},
        {"name": 'BDO Israel', "url": 'https://www.bdo.co.il', "location": 'Bnei Brak (BBC)'},
        {"name": 'Tefen Management Consulting', "url": 'http://www.tefen.com', "location": 'Tel Aviv / Central'},
        {"name": 'Aman Group', "he": 'קבוצת אמן', "url": 'https://www.aman.co.il', "location": 'Bnei Brak (BBC)'},
        {"name": 'Malam Team', "he": 'מלם תים', "url": 'https://www.malamteam.com', "location": 'Bnei Brak (BBC)'},
        {"name": 'One Technologies', "he": 'וואן טכנולוגיות', "url": 'https://www.one.co.il', "location": 'Bnei Brak (BBC)'},
        {"name": 'Matrix', "he": 'מטריקס', "url": 'https://www.matrix.co.il', "location": 'Herzliya / Tel Aviv'},
        {"name": 'Ness Technologies', "url": 'https://www.ness-tech.co.il', "location": 'Tel Aviv'},
        {"name": 'Taldor', "he": 'טלדור', "url": 'https://www.taldor.co.il', "location": 'Petah Tikva / Holon'},
        {"name": 'HMS Consulting', "url": 'https://www.hms.co.il', "location": 'Tel Aviv'},
    ],
    '🚀 Tech Startups': [
        {"name": 'Lemonade', "he": 'למונייד', "url": 'https://www.lemonade.com', "location": 'Tel Aviv', "ashby": 'lemonade'},
        {"name": 'Wix', "he": 'ויקס', "url": 'https://www.wix.com', "location": 'Tel Aviv'},
        {"name": 'HoneyBook', "url": 'https://www.honeybook.com', "location": 'Tel Aviv', "ashby": 'honeybook'},
        {"name": 'Monday.com', "url": 'https://monday.com', "location": 'Tel Aviv'},
        {"name": 'Wiz', "url": 'https://www.wiz.io', "location": 'Tel Aviv'},
        {"name": 'Moon Active', "url": 'https://www.moonactive.com', "location": 'Tel Aviv', "comeet": ('widget', 'A2.00C', '2ACD5C02AC10081008AB01560180C804')},
        {"name": 'Cyera', "url": 'https://www.cyera.io', "location": 'Tel Aviv', "comeet": ('url', 'cyera', '17.008')},
        {"name": 'Yotpo', "url": 'https://www.yotpo.com', "location": 'Tel Aviv', "greenhouse": 'yotpo'},
        {"name": 'Taboola', "url": 'https://www.taboola.com', "location": 'Tel Aviv / Ramat Gan', "greenhouse": 'taboola'},
        {"name": 'Riskified', "url": 'https://www.riskified.com', "location": 'Tel Aviv', "greenhouse": 'riskified'},
        {"name": 'Melio', "url": 'https://www.meliopayments.com', "location": 'Tel Aviv', "greenhouse": 'melio'},
        {"name": 'Lusha', "url": 'https://www.lusha.com', "location": 'Tel Aviv'},
        {"name": 'Connecteam', "url": 'https://connecteam.com', "location": 'Tel Aviv', "greenhouse": 'connecteam'},
        {"name": 'Similarweb', "url": 'https://www.similarweb.com', "location": 'Tel Aviv', "greenhouse": 'similarweb'},
        {"name": 'IronSource', "he": 'Unity', "url": 'https://www.ironsrc.com', "location": 'Tel Aviv'},
        {"name": 'HiBob', "url": 'https://www.hibob.com', "location": 'Tel Aviv'},
        {"name": 'Fiverr', "url": 'https://www.fiverr.com', "location": 'Tel Aviv', "comeet": ('url', 'fiverr', '60.002')},
        {"name": 'Check Point', "url": 'https://www.checkpoint.com', "location": 'Tel Aviv'},
        {"name": 'Outbrain', "url": 'https://www.outbrain.com', "location": 'Tel Aviv'},
        {"name": 'WalkMe', "url": 'https://www.walkme.com', "location": 'Tel Aviv', "lever": 'walkme'},
        {"name": 'Gong', "url": 'https://www.gong.io', "location": 'Tel Aviv / Ramat Gan'},
        {"name": 'Snyk', "url": 'https://snyk.io', "location": 'Tel Aviv'},
        {"name": 'SentinelOne', "url": 'https://www.sentinelone.com', "location": 'Tel Aviv'},
        {"name": 'Palo Alto Networks', "url": 'https://www.paloaltonetworks.com', "location": 'Tel Aviv'},
        {"name": 'Logz.io', "url": 'https://logz.io', "location": 'Tel Aviv', "lever": 'logz'},
        {"name": 'BigID', "url": 'https://bigid.com', "location": 'Tel Aviv', "greenhouse": 'bigid'},
        {"name": 'Orca Security', "url": 'https://orca.security', "location": 'Tel Aviv', "greenhouse": 'orcasecurity'},
        {"name": 'Cato Networks', "url": 'https://www.catonetworks.com', "location": 'Tel Aviv', "greenhouse": 'catonetworks'},
        {"name": 'SciPlay', "url": 'https://www.sciplay.com', "location": 'Tel Aviv'},
        {"name": 'Crazy Labs', "url": 'https://www.crazylabs.com', "location": 'Tel Aviv'},
        {"name": 'Beach Bum', "url": 'https://www.beachbum.com', "location": 'Tel Aviv'},
        {"name": 'Own Company', "url": 'https://www.owndata.com', "location": 'Tel Aviv'},
        {"name": 'Via Transportation', "url": 'https://ridewithvia.com', "location": 'Tel Aviv'},
        {"name": 'Artlist', "url": 'https://artlist.io', "location": 'Tel Aviv'},
        {"name": 'Guesty', "url": 'https://www.guesty.com', "location": 'Tel Aviv'},
        {"name": 'Gloat', "url": 'https://www.gloat.com', "location": 'Tel Aviv', "comeet": ('widget', 'E5.000', '5E02340002F0017800234011A01780')},
        {"name": 'Papaya Gaming', "url": 'https://www.papayagaming.com', "location": 'Tel Aviv'},
        {"name": 'Bringg', "url": 'https://www.bringg.com', "location": 'Tel Aviv', "greenhouse": 'bringg'},
        {"name": 'Trigo', "url": 'https://www.trigoretail.com', "location": 'Tel Aviv'},
        {"name": 'Optibus', "url": 'https://www.optibus.com', "location": 'Tel Aviv'},
        {"name": 'Overwolf', "url": 'https://www.overwolf.com', "location": 'Tel Aviv', "comeet": ('widget', 'B1.001', '1B16C4BD7005131B1A26F391B1')},
        {"name": 'Riverside.fm', "url": 'https://riverside.fm', "location": 'Tel Aviv', "comeet": ('url', 'riverside-fm', '66.009')},
        {"name": 'Walnut', "url": 'https://www.walnut.io', "location": 'Tel Aviv'},
        {"name": 'Torq', "url": 'https://torq.io', "location": 'Tel Aviv', "greenhouse": 'torq'},
        {"name": 'Zesty', "url": 'https://zesty.tech', "location": 'Tel Aviv'},
        {"name": 'Pecan.ai', "url": 'https://www.pecan.ai', "location": 'Tel Aviv'},
        {"name": 'BigPanda', "url": 'https://bigpanda.io', "location": 'Tel Aviv'},
        {"name": 'Bizzabo', "url": 'https://www.bizzabo.com', "location": 'Tel Aviv', "comeet": ('url', 'bizzabo', 'A5.000')},
        {"name": 'Explorium', "url": 'https://www.explorium.ai', "location": 'Tel Aviv', "comeet": ('url', 'explorium', 'B4.00E')},
        {"name": 'Tailor Brands', "url": 'https://www.tailorbrands.com', "location": 'Tel Aviv', "comeet": ('widget', '94.009', '49916FD16FD24C89320DCB296116FD2961')},
        {"name": 'Bookaway', "url": 'https://www.bookaway.com', "location": 'Tel Aviv'},
        {"name": 'Remilk', "url": 'https://www.remilk.com', "location": 'Tel Aviv'},
        {"name": 'Immunai', "url": 'https://www.immunai.com', "location": 'Tel Aviv', "comeet": ('url', 'immunai', '37.009')},
        {"name": 'Hailo', "he": 'היילו', "url": 'https://hailo.ai', "location": 'Tel Aviv'},
        {"name": 'Redis', "he": 'רדיס', "url": 'https://redis.com', "location": 'Tel Aviv', "ashby": 'redis'},
        {"name": 'SuperPlay', "url": 'https://www.superplay.co', "location": 'Tel Aviv', "comeet": ('widget', '28.003', '82330D228AF208C208C493B30D2208C38F538F5')},
        {"name": 'DoubleVerify', "url": 'https://www.doubleverify.com', "location": 'Tel Aviv', "greenhouse": 'doubleverify'},
        {"name": 'OpenWeb', "url": 'https://www.openweb.com', "location": 'Tel Aviv', "greenhouse": 'openweb'},
        {"name": 'Earnix', "url": 'https://earnix.com', "location": 'Givatayim'},
        {"name": 'Elementor', "url": 'https://elementor.com', "location": 'Ramat Gan', "comeet": ('widget', 'A3.00F', '3AF126BB0D161A3AF161A00B0D126B')},
        {"name": 'DealHub', "url": 'https://dealhub.io', "location": 'Holon'},
        {"name": 'PandoLogic', "url": 'https://pandologic.com', "location": 'Bnei Brak (BBC)'},
        {"name": 'JFrog', "url": 'https://jfrog.com', "location": 'Netanya / Tel Aviv', "greenhouse": 'jfrog'},
        {"name": 'Lightricks', "url": 'https://www.lightricks.com', "location": 'Jerusalem / Tel Aviv', "greenhouse": 'lightricks'},
        {"name": 'Forter', "url": 'https://forter.com', "location": 'Tel Aviv', "greenhouse": 'forter'},
        {"name": 'MyHeritage', "he": 'מייהריטג׳', "url": 'https://www.myheritage.com', "location": 'Or Yehuda', "greenhouse": 'myheritage'},
        {"name": 'Optimove', "url": 'https://www.optimove.com', "location": 'Tel Aviv', "greenhouse": 'optimove'},
        {"name": 'Transmit Security', "url": 'https://transmitsecurity.com', "location": 'Tel Aviv', "greenhouse": 'transmitsecurity'},
        {"name": 'Innovid', "url": 'https://www.innovid.com', "location": 'Tel Aviv', "greenhouse": 'innovid'},
        {"name": 'Axonius', "url": 'https://www.axonius.com', "location": 'Tel Aviv', "greenhouse": 'axonius'},
        {"name": 'LivePerson', "url": 'https://www.liveperson.com', "location": 'Tel Aviv', "greenhouse": 'liveperson'},
        {"name": 'Cloudinary', "url": 'https://cloudinary.com', "location": 'Israel', "lever": 'cloudinary'},
        {"name": 'Island', "url": 'https://island.io', "location": 'Tel Aviv'},
        {"name": 'Pyramid Analytics', "url": 'https://www.pyramidanalytics.com', "location": 'Tel Aviv'},
        {"name": 'vcita', "url": 'https://www.vcita.com', "location": 'Bat Yam'},
        {"name": 'SundaySky', "url": 'https://www.sundaysky.com', "location": 'Tel Aviv'},
        {"name": 'Aquant', "url": 'https://www.aquant.ai', "location": 'Tel Aviv', "ashby": 'aquant'},
        {"name": 'IRONSCALES', "url": 'https://ironscales.com', "location": 'Tel Aviv'},
        {"name": 'Foretellix', "url": 'https://foretellix.com', "location": 'Kfar Saba'},
        {"name": 'Perception Point', "url": 'https://perception-point.io', "location": 'Tel Aviv'},
        {"name": 'SQream', "url": 'https://sqream.com', "location": 'Tel Aviv'},
        {"name": 'Demostack', "url": 'https://www.demostack.com', "location": 'Tel Aviv'},
        {"name": 'SparkBeyond', "url": 'https://www.sparkbeyond.com', "location": 'Tel Aviv'},
        {"name": 'ARMO', "url": 'https://www.armosec.io', "location": 'Tel Aviv'},
        {"name": 'Evinced', "url": 'https://www.evinced.com', "location": 'Tel Aviv'},
        {"name": 'Reco Labs', "he": 'רקו', "url": 'https://www.reco.ai', "location": 'Tel Aviv'},
        {"name": 'Swimm', "url": 'https://swimm.io', "location": 'Tel Aviv'},
        {"name": 'Vicarius', "url": 'https://www.vicarius.io', "location": 'Tel Aviv'},
        {"name": 'Blink Ops', "url": 'https://www.blinkops.com', "location": 'Tel Aviv'},
        {"name": 'Skyhawk Security', "url": 'https://www.skyhawk.security', "location": 'Tel Aviv'},
        {"name": 'Solvo', "url": 'https://www.solvo.cloud', "location": 'Tel Aviv'},
        {"name": 'Sensibo', "url": 'https://sensibo.com', "location": 'Tel Aviv'},
        {"name": 'Harmonya', "url": 'https://www.harmonya.com', "location": 'Tel Aviv'},
        {"name": 'Rep AI', "url": 'https://www.hellorep.ai', "location": 'Tel Aviv'},
        {"name": 'DBmaestro', "url": 'https://www.dbmaestro.com', "location": 'Or Yehuda'},
        {"name": 'Kubiya', "url": 'https://kubiya.ai', "location": 'Tel Aviv'},
        {"name": 'Equally AI', "url": 'https://equally.ai', "location": 'Tel Aviv'},
        {"name": 'illumex', "url": 'https://illumex.com', "location": 'Tel Aviv'},
        {"name": 'Bright Data', "url": 'https://brightdata.com', "location": 'Netanya'},
        {"name": 'Armis', "url": 'https://www.armis.com', "location": 'Tel Aviv'},
        {"name": 'Deep Instinct', "url": 'https://www.deepinstinct.com', "location": 'Tel Aviv'},
        {"name": 'Juno Journey', "url": 'https://junojourney.com', "location": 'Tel Aviv'},
        {"name": 'Tomorrow.io', "url": 'https://www.tomorrow.io', "location": 'Tel Aviv'},
        {"name": 'Tonkean', "url": 'https://www.tonkean.com', "location": 'Tel Aviv'},
        {"name": 'Hello Heart', "url": 'https://helloheart.com', "location": 'Tel Aviv'},
        {"name": 'Cynerio', "url": 'https://www.cynerio.com', "location": 'Tel Aviv'},
    ],
    '💻 Established Tech': [
        {"name": 'CyberArk', "url": 'https://www.cyberark.com', "location": 'Petah Tikva'},
        {"name": 'Verint', "url": 'https://www.verint.com', "location": 'Herzliya'},
        {"name": 'Playtika', "url": 'https://www.playtika.com', "location": 'Herzliya'},
        {"name": 'AppsFlyer', "url": 'https://www.appsflyer.com', "location": 'Herzliya', "greenhouse": 'appsflyer'},
        {"name": 'Cognyte', "he": 'קוגנייט', "url": 'https://www.cognyte.com', "location": 'Herzliya', "comeet": ('url', 'cognyte', 'F2.009')},
        {"name": 'Infinidat', "he": 'אינפינידט', "url": 'https://www.infinidat.com', "location": 'Herzliya', "comeet": ('url', 'infinidat', 'D6.003')},
        {"name": 'Plarium', "he": 'פלאריום', "url": 'https://plarium.com', "location": 'Herzliya'},
        {"name": 'Sapiens', "he": 'סאפיינס', "url": 'https://sapiens.com', "location": 'Holon (Azrieli Center)'},
        {"name": 'Perion Network', "he": 'פריון', "url": 'https://www.perion.com', "location": 'Holon (Azrieli Center)'},
        {"name": 'Sisense', "url": 'https://www.sisense.com', "location": 'Ramat Gan', "greenhouse": 'sisense'},
        {"name": 'Kaltura', "url": 'https://corp.kaltura.com', "location": 'Ramat Gan'},
        {"name": 'Atera', "url": 'https://www.atera.com', "location": 'Tel Aviv / Ramat Gan'},
    ],
    '🌐 Global Tech Hubs': [
        {"name": 'Google Israel', "url": 'https://about.google', "location": 'Tel Aviv'},
        {"name": 'Microsoft Israel', "url": 'https://www.microsoft.com', "location": 'Herzliya / Tel Aviv'},
        {"name": 'Meta Israel', "he": 'Facebook', "url": 'https://about.meta.com', "location": 'Tel Aviv'},
        {"name": 'Amazon / AWS Israel', "url": 'https://aws.amazon.com', "location": 'Tel Aviv'},
        {"name": 'Apple Israel', "url": 'https://www.apple.com', "location": 'Herzliya'},
        {"name": 'Salesforce Israel', "url": 'https://www.salesforce.com', "location": 'Tel Aviv'},
        {"name": 'NVIDIA Israel', "url": 'https://www.nvidia.com', "location": 'Tel Aviv'},
        {"name": 'Zendesk Israel', "url": 'https://www.zendesk.com', "location": 'Tel Aviv'},
        {"name": 'IBM Israel', "url": 'https://www.ibm.com', "location": 'Tel Aviv / Petah Tikva'},
        {"name": 'Cisco Israel', "url": 'https://www.cisco.com', "location": 'Tel Aviv / Herzliya'},
        {"name": 'PayPal Israel', "url": 'https://www.paypal.com', "location": 'Tel Aviv'},
        {"name": 'Intel Israel', "url": 'https://www.intel.co.il', "location": 'Petah Tikva Area'},
        {"name": 'Oracle Israel', "url": 'https://www.oracle.com/il', "location": 'Petah Tikva'},
        {"name": 'Marvell Israel', "url": 'https://www.marvell.com', "location": 'Petah Tikva'},
        {"name": 'General Motors Israel', "he": 'GM', "url": 'https://www.gm.com', "location": 'Herzliya'},
        {"name": 'Citi Innovation Lab', "url": 'https://www.citigroup.com', "location": 'Tel Aviv'},
        {"name": 'AT&T Israel', "url": 'https://www.att.com', "location": 'Tel Aviv', "comeet": ('url', 'joinattil', '38.00A')},
    ],
    '🛒 Retail & FMCG': [
        {"name": 'Wolt', "url": 'https://wolt.com', "location": 'Tel Aviv', "greenhouse": 'wolt'},
        {"name": 'Global-e', "url": 'https://www.global-e.com', "location": 'Petah Tikva', "comeet": ('widget', '62.002', '262988131015727264C41572E4C10AE10AE')},
        {"name": 'Shufersal', "he": 'שופרסל', "url": 'https://www.shufersal.co.il', "location": 'Petah Tikva / Rishon'},
        {"name": 'Strauss Group', "he": 'שטראוס', "url": 'https://www.strauss-group.co.il', "location": 'Petah Tikva'},
        {"name": 'Osem-Nestle', "he": 'אסם', "url": 'https://www.osem.co.il', "location": 'Petah Tikva Area'},
        {"name": 'Super-Pharm', "he": 'סופר-פארם', "url": 'https://www.super-pharm.co.il', "location": 'Herzliya'},
        {"name": 'Fox Group', "he": 'Terminal X', "url": 'https://www.foxgroup.co.il', "location": 'Tel Aviv'},
        {"name": 'BuyMe', "url": 'https://buyme.co.il', "location": 'Tel Aviv', "comeet": ('url', 'buyme', 'B2.008')},
        {"name": 'Azrieli.com', "url": 'https://www.azrieli.com', "location": 'Tel Aviv'},
        {"name": 'Yango Israel', "url": 'https://yango.com', "location": 'Tel Aviv'},
        {"name": 'Paz Oil Company', "he": 'פז', "url": 'https://www.paz.co.il', "location": 'Herzliya'},
        {"name": 'Electra Consumer Products', "url": 'https://www.ecp.co.il', "location": 'Holon / Rishon'},
    ],
    '🏥 Pharma & MedTech': [
        {"name": 'Teva Pharmaceuticals', "url": 'https://www.tevapharm.com', "location": 'Tel Aviv (Ramat HaChayal)'},
        {"name": 'Medison Pharma', "url": 'https://www.medisonpharma.com', "location": 'Petah Tikva', "comeet": ('widget', '67.00A', '76A2C7C163E33E625122C7C1DA8ED476A33E6')},
        {"name": 'Lumenis', "url": 'https://www.lumenis.com', "location": 'Herzliya', "comeet": ('widget', 'A1.00C', '1AC6B0A08F0C6B085C85CD60F0C1AC')},
        {"name": 'SolarEdge', "url": 'https://www.solaredge.com', "location": 'Herzliya'},
        {"name": 'Pango', "url": 'https://www.pango.co.il', "location": 'Petah Tikva', "comeet": ('url', 'pango', '59.002')},
        {"name": 'Elmo Motion Control', "url": 'https://www.elmomotioncontrol.com', "location": 'Petah Tikva'},
        {"name": 'Dot Compliance', "url": 'https://www.dotcompliance.com', "location": "Ra'anana"},
    ],
    '🏗️ Industrial': [
        {"name": 'Israel Aerospace Industries', "he": 'IAI', "url": 'https://www.iai.co.il', "location": 'Petah Tikva / Border'},
        {"name": 'Israel Electric Corp', "he": 'חברת החשמל', "url": 'https://www.iec.co.il', "location": 'Tel Aviv'},
        {"name": 'Mekorot', "he": 'מקורות', "url": 'https://www.mekorot.co.il', "location": 'Tel Aviv'},
        {"name": 'Shikun & Binui', "he": 'שיכון ובינוי', "url": 'https://www.shikunbinui.com', "location": 'Tel Aviv Area'},
        {"name": 'Dan Transportation', "he": 'דן', "url": 'https://www.dan.co.il', "location": 'Tel Aviv'},
        {"name": 'Egged', "he": 'אגד', "url": 'https://www.egged.co.il', "location": 'Tel Aviv / Holon'},
        {"name": 'NTA', "he": 'נת"ע', "url": 'https://www.nta.co.il', "location": 'Tel Aviv'},
        {"name": 'El Al', "he": 'אל על', "url": 'https://www.elal.com', "location": 'Tel Aviv / Ben Gurion Area'},
        {"name": 'Pelephone', "he": 'פלאפון', "url": 'https://www.pelephone.co.il', "location": 'Givatayim'},
        {"name": 'Tadiran', "he": 'תדיראן', "url": 'https://www.tadiran-group.co.il', "location": 'Holon Area'},
        {"name": 'Azrieli Group', "he": 'קבוצת עזריאלי', "url": 'https://www.azrieligroup.com', "location": 'Tel Aviv'},
        {"name": 'Amot Investments', "he": 'אמות', "url": 'https://www.amot.co.il', "location": 'Tel Aviv'},
        {"name": 'Gilat Satellite Networks', "url": 'https://www.gilat.com', "location": 'Petah Tikva'},
        {"name": 'Amdocs', "he": 'אמדוקס', "url": 'https://www.amdocs.com', "location": 'Herzliya'},
    ],
    '🛡️ InsurTech': [
        {"name": 'EasySend', "url": 'https://www.easysend.io', "location": 'Tel Aviv'},
        {"name": 'Planck', "url": 'https://planckdata.com', "location": 'Tel Aviv'},
        {"name": 'Five Sigma', "url": 'https://www.five-sigma.com', "location": 'Tel Aviv'},
    ],
    '📣 AdTech & MarTech': [
        {"name": 'Skai', "he": 'לשעבר Kenshoo', "url": 'https://skai.io', "location": 'Tel Aviv'},
        {"name": 'Bigabid', "url": 'https://www.bigabid.com', "location": 'Tel Aviv'},
        {"name": 'Nexxen', "url": 'https://www.nexxen.com', "location": 'Tel Aviv', "ashby": 'nexxen'},
        {"name": 'Anzu.io', "url": 'https://www.anzu.io', "location": 'Tel Aviv'},
    ],
    '🏠 PropTech & ConTech': [
        {"name": 'Buildots', "url": 'https://buildots.com', "location": 'Tel Aviv'},
        {"name": 'Placer.ai', "url": 'https://www.placer.ai', "location": 'Ramat Gan'},
        {"name": 'Swapp', "url": 'https://www.swapp.ai', "location": 'Tel Aviv'},
        {"name": 'Lendlord', "url": 'https://lendlord.io', "location": 'Tel Aviv'},
    ],
    '⚖️ Legal Tech': [
        {"name": 'LawGeex', "url": 'https://www.lawgeex.com', "location": 'Tel Aviv'},
        {"name": 'Darrow', "url": 'https://darrow.ai', "location": 'Tel Aviv'},
    ],
    '🚗 Mobility & AutoTech': [
        {"name": 'Fullpath', "he": 'לשעבר AutoLeadStar', "url": 'https://www.fullpath.com', "location": 'Jerusalem'},
        {"name": 'Nexar', "url": 'https://www.nexar.com', "location": 'Tel Aviv'},
        {"name": 'REE Automotive', "url": 'https://www.ree.auto', "location": 'Tel Aviv'},
    ],
    '🩺 HealthTech & Digital Health': [
        {"name": 'Intuition Robotics', "url": 'https://www.intuitionrobotics.com', "location": 'Ramat Gan'},
        {"name": 'Belong.Life', "url": 'https://belong.life', "location": 'Petah Tikva'},
        {"name": 'Kahun', "url": 'https://www.kahun.com', "location": 'Tel Aviv'},
    ],
    '🎮 Gaming': [
        {"name": 'Ilyon Games', "he": 'איליון', "url": 'https://www.ilyon.net', "location": 'Rosh HaAyin'},
        {"name": 'Tangelo Games', "url": 'https://tangelogames.com', "location": 'Tel Aviv'},
        {"name": 'NeoGames', "url": 'https://www.neogames.com', "location": 'Tel Aviv'},
    ],
    '📚 EdTech': [
        {"name": 'JoyTunes', "he": 'ג׳וי-טיונס', "url": 'https://www.joytunes.com', "location": 'Tel Aviv'},
        {"name": 'Symbolab', "url": 'https://www.symbolab.com', "location": 'Tel Aviv'},
        {"name": 'CodeMonkey Studios', "url": 'https://www.codemonkey.com', "location": 'Tel Aviv'},
        {"name": 'TinyTap', "url": 'https://www.tinytap.com', "location": 'Tel Aviv'},
        {"name": 'Annoto', "url": 'https://www.annoto.net', "location": 'Ramat Gan'},
        {"name": 'Edusoft', "url": 'https://edusoftlearning.com', "location": 'Rosh HaAyin'},
        {"name": 'eTeacher Group', "url": 'https://www.eteachergroup.com', "location": 'Ramat Gan'},
    ],
    '👥 HR-Tech': [
        {"name": 'Papaya Global', "url": 'https://www.papayaglobal.com', "location": 'Tel Aviv'},
        {"name": 'HiredScore', "url": 'https://hiredscore.com', "location": 'Tel Aviv'},
    ],
    '📡 Telecom': [
        {"name": 'Cellcom Israel', "he": 'סלקום', "url": 'https://www.cellcom.co.il', "location": 'Netanya'},
        {"name": 'Partner Communications', "he": 'פרטנר', "url": 'https://www.partner.co.il', "location": 'Rosh HaAyin'},
        {"name": 'Bezeq', "he": 'בזק', "url": 'https://www.bezeq.co.il', "location": 'Tel Aviv'},
        {"name": 'Hot Mobile', "he": 'הוט מובייל', "url": 'https://www.hotmobile.co.il', "location": 'Yakum'},
    ],
    '🎬 Media & Entertainment': [
        {"name": 'Keshet Media Group', "he": 'קשת', "url": 'https://www.keshetinternational.com', "location": 'Tel Aviv'},
        {"name": 'Yes', "he": 'יס', "url": 'https://www.yes.co.il', "location": 'Kfar Saba'},
        {"name": 'Walla! Communications', "he": 'וואלה', "url": 'https://www.walla.co.il', "location": 'Tel Aviv'},
        {"name": 'Yedioth Ahronoth / Ynet', "he": 'ידיעות אחרונות / ynet', "url": 'https://www.ynet.co.il', "location": 'Tel Aviv'},
    ],
    '🌱 Climate & AgriTech': [
        {"name": 'Fermata', "url": 'https://www.fermata.tech', "location": 'Israel'},
        {"name": 'Greeneye Technology', "url": 'https://greeneye.ag', "location": 'Israel'},
        {"name": 'UBQ Materials', "url": 'https://www.ubqmaterials.com', "location": "Tze'elim"},
        {"name": 'Electreon', "url": 'https://electreon.com', "location": 'Beit Yanai'},
        {"name": 'H2Pro', "url": 'https://www.h2pro.co', "location": 'Caesarea'},
        {"name": 'SupPlant', "url": 'https://supplant.me', "location": 'Afula'},
        {"name": 'N-Drip', "url": 'https://ndrip.com', "location": 'Kfar Saba'},
    ],
}

TEXTS = {
    "he": {
        "app_title": "מנוע חיפוש עבודה",
        "nav_home": "🏠 ראשי",
        "nav_profile": "👤 פרופיל",
        "nav_jobs": "🔍 חיפוש משרות",
        "nav_cv": "📄 בניית קו\"ח",
        "nav_cover": "✉️ מכתב מקדים",
        "nav_companies": "🏢 חברות",
        "nav_tracker": "🚀 מעקב הגשות",
        "nav_advisor": "🎯 יועץ קריירה",
        "search_placeholder": "חפש משרה, חברה או תפקיד...",
        "match_score": "התאמה",
        "apply_now": "הגש מועמדות",
        "build_cv": "בנה קו\"ח",
        "save_job": "שמור משרה",
        "no_jobs": "לא נמצאו משרות. נסה לשנות את מונחי החיפוש.",
        "profile_complete": "פרופיל מלא",
        "loading": "טוען...",
        "error_api": "שגיאה: נא להזין ANTHROPIC_API_KEY ב-.env",
    },
    "en": {
        "app_title": "Job Search Engine",
        "nav_home": "🏠 Home",
        "nav_profile": "👤 Profile",
        "nav_jobs": "🔍 Job Search",
        "nav_cv": "📄 CV Builder",
        "nav_cover": "✉️ Cover Letter",
        "nav_companies": "🏢 Companies",
        "nav_tracker": "🚀 Application Tracker",
        "nav_advisor": "🎯 Career Advisor",
        "search_placeholder": "Search job title, company, or keyword...",
        "match_score": "Match",
        "apply_now": "Apply Now",
        "build_cv": "Build CV",
        "save_job": "Save Job",
        "no_jobs": "No jobs found. Try adjusting your search.",
        "profile_complete": "Profile Complete",
        "loading": "Loading...",
        "error_api": "Error: Please set ANTHROPIC_API_KEY in .env",
    },
}
